# Generated by Django 5.0.3 on 2024-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Innovative_project", "0002_alter_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
