# Generated by Django 5.0.4 on 2024-05-08 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovative_project', '0002_host_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_id',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='hostname',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='host_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Innovative_project.host'),
        ),
    ]
