# Generated by Django 5.0.4 on 2024-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovative_project', '0003_host_address_host_email_host_host_id_host_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='host_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
