# Generated by Django 5.0.3 on 2024-05-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Innovative_project", "0003_host_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="password",
        ),
    ]
